export enum UserSignupActionType {
    USER_SIGNUP_REQUEST = 'USER_SIGNUP_REQUEST',
    USER_SIGNUP_SUCCESS = 'USER_SIGNUP_SUCCESS',
    USER_SIGNUP_FAIL = 'USER_SIGNUP_FAIL',
    LOAD_USER_PROFILE = 'LOAD_USER_PROFILE',
    USER_LOGOUT_REQUEST = 'USER_LOGOUT_REQUEST',
    USER_LOGOUT_SUCCESS = 'USER_LOGOUT_SUCCESS',
}

export enum UserSigninActionType {
    USER_SIGNIN_REQUEST = 'USER_SIGNIN_REQUEST',
    USER_SIGNIN_SUCCESS = 'USER_SIGNIN_SUCCESS',
    USER_SIGNIN_FAIL = 'USER_SIGNIN_FAIL',
    LOAD_USER_PROFILE = 'LOAD_USER_PROFILE',
    USER_LOGOUT_REQUEST = 'USER_LOGOUT_REQUEST',
    USER_LOGOUT_SUCCESS = 'USER_LOGOUT_SUCCESS',
}



