export enum CreateConversationOrRoomActionType {
    CREATE_CONVERSATION_OR_ROOM_REQUEST = 'CREATE_CONVERSATION_OR_ROOM_REQUEST',
    CREATE_CONVERSATION_OR_ROOM_SUCCESS = 'CREATE_CONVERSATION_OR_ROOM_SUCCESS',
    CREATE_CONVERSATION_OR_ROOM_FAIL = 'CREATE_CONVERSATION_OR_ROOM_FAIL'
}

export enum GetMyChatsActionType {
    GET_MY_CHATS_REQUEST = 'GET_MY_CHATS_REQUEST',
    GET_MY_CHATS_SUCCESS = 'GET_MY_CHATS_SUCCESS',
    GET_MY_CHATS_FAIL = 'GET_MY_CHATS_FAIL'
}

export enum GetConversationsActionType {
    GET_CONVERSATIONS_REQUEST = 'GET_CONVERSATIONS_REQUEST',
    GET_CONVERSATIONS_SUCCESS = 'GET_CONVERSATIONS_SUCCESS',
    GET_CONVERSATIONS_FAIL = 'GET_CONVERSATIONS_FAIL'
}

export enum AddMembersToRoomActionType {
    ADD_MEMBERS_TO_ROOM_REQUEST = 'ADD_MEMBERS_TO_ROOM_REQUEST',
    ADD_MEMBERS_TO_ROOM_SUCCESS = 'ADD_MEMBERS_TO_ROOM_SUCCESS',
    ADD_MEMBERS_TO_ROOM_FAIL = 'ADD_MEMBERS_TO_ROOM_FAIL'
}