export enum CreateConversationOrRoomActionType {
    CREATE_CONVERSATION_OR_ROOM_REQUEST = 'CREATE_CONVERSATION_OR_ROOM_REQUEST',
    CREATE_CONVERSATION_OR_ROOM_SUCCESS = 'CREATE_CONVERSATION_OR_ROOM_SUCCESS',
    CREATE_CONVERSATION_OR_ROOM_FAIL = 'CREATE_CONVERSATION_OR_ROOM_FAIL'
}