export enum CreateConversationOrRoomActionType {
    CREATE_CONVERSATION_OR_ROOM_REQUEST = 'CREATE_CONVERSATION_OR_ROOM_REQUEST',
    CREATE_CONVERSATION_OR_ROOM_SUCCESS = 'CREATE_CONVERSATION_OR_ROOM_SUCCESS',
    CREATE_CONVERSATION_OR_ROOM_FAIL = 'CREATE_CONVERSATION_OR_ROOM_FAIL'
}

export enum GetMyChatsActionType {
    GET_MY_CHATS_REQUEST = 'GET_MY_CHATS_REQUEST',
    GET_MY_CHATS_SUCCESS = 'GET_MY_CHATS_SUCCESS',
    GET_MY_CHATS_FAIL = 'GET_MY_CHATS_FAIL'
}