export enum GetUserFollowersActionType {
    GET_USERFOLLOWERS_REQUEST = 'GET_USERFOLLOWERS_REQUEST',
    GET_USERFOLLOWERS_SUCCESS = 'GET_USERFOLLOWERS_SUCCESS',
    GET_USERFOLLOWERS_FAIL = 'GET_USERFOLLOWERS_FAIL'
}

export enum GetFollowingUsersActionType {
    GET_FOLLOWINGUSERS_REQUEST = 'GET_FOLLOWINGUSERS_REQUEST',
    GET_FOLLOWINGUSERS_SUCCESS = 'GET_FOLLOWINGUSERS_SUCCESS',
    GET_FOLLOWINGUSERS_FAIL = 'GET_FOLLOWINGUSERS_FAIL'
}

