export enum CreatePostActionType {
    CREATE_POST_REQUEST = "CREATE_POST_REQUEST",
    CREATE_POST_SUCCESS = "CREATE_POST_SUCCESS",
    CREATE_POST_FAIL = "CREATE_POST_FAIL"
}

export enum GetFeedActionType {
    GET_FEED_REQUEST = 'GET_FEED_REQUEST',
    GET_FEED_SUCCESS = 'GET_FEED_SUCCESS',
    GET_FEED_FAIL = 'GET_FEED_FAIL'
}

export enum GetMyPostsActionType {
    GET_MYPOST_REQUEST = 'GET_MYPOST_REQUEST',
    GET_MYPOST_SUCCESS = 'GET_MYPOST_SUCCESS',
    GET_MYPOST_FAIL = 'GET_MYPOST_FAIL'
}

export enum EditPostActionType {
    EDIT_POST_REQUEST = 'EDIT_POST_REQUEST',
    EDIT_POST_SUCCESS = 'EDIT_POST_SUCCESS',
    EDIT_POST_FAIL = 'EDIT_POST_FAIL'
}

export enum DeletePostActionType {
    DELETE_POST_REQUEST = 'DELETE_POST_REQUEST',
    DELETE_POST_SUCCESS = 'DELETE_POST_SUCCESS',
    DELETE_POST_FAIL = 'DELETE_POST_FAIL'
}

export enum GetPostLikesActionType {
    GET_LIKES_REQUEST = 'GET_LIKES_REQUEST',
    GET_LIKES_SUCCESS = 'GET_LIKES_SUCCESS',
    GET_LIKES_FAIL = 'GET_LIKES_FAIL'
}

export enum GetPostCommentsActionType {
    GET_COMMENTS_REQUEST = 'GET_COMMENTS_REQUEST',
    GET_COMMENTS_SUCCESS = 'GET_COMMENTS_SUCCESS',
    GET_COMMENTS_FAIL = 'GET_COMMENTS_FAIL'
}

export enum PostLikeActionType {
    POST_LIKE_REQUEST = 'POST_LIKE_REQUEST',
    POST_LIKE_SUCCESS = 'POST_LIKE_SUCCESS',
    POST_LIKE_FAIL = 'POST_LIKE_FAIL'
}

export enum PostCommentActionType {
    POST_COMMENT_REQUEST = 'POST_COMMENT_REQUEST',
    POST_COMMENT_SUCCESS = 'POST_COMMENT_SUCCESS',
    POST_COMMENT_FAIL = 'POST_COMMENT_FAIL'
}

export enum GetUsersPostsActionType {
    GET_USERSPOST_REQUEST = 'GET_USERSPOST_REQUEST',
    GET_USERSPOST_SUCCESS = 'GET_USERSPOST_SUCCESS',
    GET_USERSPOST_FAIL = 'GET_USERSPOST_FAIL'
}

export enum TeamJoinActionType {
    TEAM_JOIN_REQUEST = 'TEAM_JOIN_REQUEST',
    TEAM_JOIN_SUCCESS = 'TEAM_JOIN_SUCCESS',
    TEAM_JOIN_FAIL = 'TEAM_JOIN_FAIL'
}