export enum CreatePostActionType {
    CREATE_POST_REQUEST = "CREATE_POST_REQUEST",
    CREATE_POST_SUCCESS = "CREATE_POST_SUCCESS",
    CREATE_POST_FAIL = "CREATE_POST_FAIL"
}

export enum GetMyPostsActionType {
    GET_MYPOST_REQUEST = 'GET_MYPOST_REQUEST',
    GET_MYPOST_SUCCESS = 'GET_MYPOST_SUCCESS',
    GET_MYPOST_FAIL = 'GET_MYPOST_FAIL'
}