export enum CreatePostActionType {
    CREATE_POST_REQUEST = "CREATE_POST_REQUEST",
    CREATE_POST_SUCCESS = "CREATE_POST_SUCCESS",
    CREATE_POST_FAIL = "CREATE_POST_FAIL"
}

export enum GetFeedActionType {
    GET_FEED_REQUEST = 'GET_FEED_REQUEST',
    GET_FEED_SUCCESS = 'GET_FEED_SUCCESS',
    GET_FEED_FAIL = 'GET_FEED_FAIL'
}

export enum GetMyPostsActionType {
    GET_MYPOST_REQUEST = 'GET_MYPOST_REQUEST',
    GET_MYPOST_SUCCESS = 'GET_MYPOST_SUCCESS',
    GET_MYPOST_FAIL = 'GET_MYPOST_FAIL'
}

export enum EditPostActionType {
    EDIT_POST_REQUEST = 'EDIT_POST_REQUEST',
    EDIT_POST_SUCCESS = 'EDIT_POST_SUCCESS',
    EDIT_POST_FAIL = 'EDIT_POST_FAIL'
}

export enum DeletePostActionType {
    DELETE_POST_REQUEST = 'DELETE_POST_REQUEST',
    DELETE_POST_SUCCESS = 'DELETE_POST_SUCCESS',
    DELETE_POST_FAIL = 'DELETE_POST_FAIL'
}