export enum GetMyProjectActionType {
    GET_MYPROJECT_REQUEST = 'GET_MYPROJECT_REQUEST',
    GET_MYPROJECT_SUCCESS = 'GET_MYPROJECT_SUCCESS',
    GET_MYPROJECT_FAIL = 'GET_MYPROJECT_FAIL'
}

export enum GetProjectDetailsActionType {
    GET_PROJECT_DETAILS_REQUEST = 'GET_PROJECT_DETAILS_REQUEST',
    GET_PROJECT_DETAILS_SUCCESS = 'GET_PROJECT_DETAILS_SUCCESS',
    GET_PROJECT_DETAILS_FAIL = 'GET_PROJECT_DETAILS_FAIL'
}