export enum GetMyProjectActionType {
    GET_MYPROJECT_REQUEST = 'GET_MYPROJECT_REQUEST',
    GET_MYPROJECT_SUCCESS = 'GET_MYPROJECT_SUCCESS',
    GET_MYPROJECT_FAIL = 'GET_MYPROJECT_FAIL'
}

export enum GetProjectDetailsActionType {
    GET_PROJECT_DETAILS_REQUEST = 'GET_PROJECT_DETAILS_REQUEST',
    GET_PROJECT_DETAILS_SUCCESS = 'GET_PROJECT_DETAILS_SUCCESS',
    GET_PROJECT_DETAILS_FAIL = 'GET_PROJECT_DETAILS_FAIL'
}

export enum AddProjectDescriptionActionType {
    ADD_PROJECT_DESCRIPTION_REQUEST = 'ADD_PROJECT_DESCRIPTION_REQUEST',
    ADD_PROJECT_DESCRIPTION_SUCCESS = 'ADD_PROJECT_DESCRIPTION_SUCCESS',
    ADD_PROJECT_DESCRIPTION_FAIL = 'ADD_PROJECT_DESCRIPTION_FAIL'
}

export enum ManageTeamRoleActionType {
    MANAGE_TEAM_ROLE_REQUEST = 'MANAGE_TEAM_ROLE_REQUEST',
    MANAGE_TEAM_ROLE_SUCCESS = 'MANAGE_TEAM_ROLE_SUCCESS',
    MANAGE_TEAM_ROLE_FAIL = 'MANAGE_TEAM_ROLE_FAIL'
}

export enum LeaveOrRemoveMembersActionType {
    LEAVE_OR_REMOVE_MEMBERS_REQUEST = 'LEAVE_OR_REMOVE_MEMBERS_REQUEST',
    LEAVE_OR_REMOVE_MEMBERS_SUCCESS = 'LEAVE_OR_REMOVE_MEMBERS_SUCCESS',
    LEAVE_OR_REMOVE_MEMBERS_FAIL = 'LEAVE_OR_REMOVE_MEMBERS_FAIL'
}

export enum ProjectTodoActionType {
    PROJECT_TODO_REQUEST = 'PROJECT_TODO_REQUEST',
    PROJECT_TODO_SUCCESS = 'PROJECT_TODO_SUCCESS',
    PROJECT_TODO_FAIL = 'PROJECT_TODO_FAIL'
}

export enum ProjectTaskActionType {
    PROJECT_TASK_REQUEST = 'PROJECT_TASK_REQUEST',
    PROJECT_TASK_SUCCESS = 'PROJECT_TASK_SUCCESS',
    PROJECT_TASK_FAIL = 'PROJECT_TASK_FAIL'
}

export enum ProjectTaskIsCompleteActionType {
    PROJECT_TASK_ISCOMPLETE_REQUEST = 'PROJECT_TASK_ISCOMPLETE_REQUEST',
    PROJECT_TASK_ISCOMPLETE_SUCCESS = 'PROJECT_TASK_ISCOMPLETE_SUCCESS',
    PROJECT_TASK_ISCOMPLETE_FAIL = 'PROJECT_TASK_ISCOMPLETE_FAIL'
}

export enum ProjectTaskDeleteActionType {
    PROJECT_TASK_DELETE_REQUEST = 'PROJECT_TASK_DELETE_REQUEST',
    PROJECT_TASK_DELETE_SUCCESS = 'PROJECT_TASK_DELETE_SUCCESS',
    PROJECT_TASK_DELETE_FAIL = 'PROJECT_TASK_DELETE_FAIL'
}