export enum GetMyProjectActionType {
    GET_MYPROJECT_REQUEST = 'GET_MYPROJECT_REQUEST',
    GET_MYPROJECT_SUCCESS = 'GET_MYPROJECT_SUCCESS',
    GET_MYPROJECT_FAIL = 'GET_MYPROJECT_FAIL'
}

export enum GetProjectDetailsActionType {
    GET_PROJECT_DETAILS_REQUEST = 'GET_PROJECT_DETAILS_REQUEST',
    GET_PROJECT_DETAILS_SUCCESS = 'GET_PROJECT_DETAILS_SUCCESS',
    GET_PROJECT_DETAILS_FAIL = 'GET_PROJECT_DETAILS_FAIL'
}

export enum AddProjectDescriptionActionType {
    ADD_PROJECT_DESCRIPTION_REQUEST = 'ADD_PROJECT_DESCRIPTION_REQUEST',
    ADD_PROJECT_DESCRIPTION_SUCCESS = 'ADD_PROJECT_DESCRIPTION_SUCCESS',
    ADD_PROJECT_DESCRIPTION_FAIL = 'ADD_PROJECT_DESCRIPTION_FAIL'
}

export enum ManageTeamRoleActionType {
    MANAGE_TEAM_ROLE_REQUEST = 'MANAGE_TEAM_ROLE_REQUEST',
    MANAGE_TEAM_ROLE_SUCCESS = 'MANAGE_TEAM_ROLE_SUCCESS',
    MANAGE_TEAM_ROLE_FAIL = 'MANAGE_TEAM_ROLE_FAIL'
}