export enum UserProfileDetailsActionType {
    USER_PROFILE_DETAILS_REQUEST = 'USER_PROFILE_DETAILS_REQUEST',
    USER_PROFILE_DETAILS_SUCCESS = 'USER_PROFILE_DETAILS_SUCCESS',
    USER_PROFILE_DETAILS_FAIL = 'USER_PROFILE_DETAILS_FAIL'

}


export enum UserEditProfileActionType {
    USER_EDIT_PROFILE_REQUEST = 'USER_EDIT_PROFILE_REQUEST',
    USER_EDIT_PROFILE_SUCCESS = 'USER_EDIT_PROFILE_SUCCESS',
    USER_EDIT_PROFILE_FAIL = 'USER_EDIT_PROFILE_FAIL',
}

export enum GetUserDetailsActionType {
    GET_USERDETAILS_REQUEST = 'GET_USERDETAILS_REQUEST',
    GET_USERDETAILS_SUCCESS = 'GET_USERDETAILS_SUCCESS',
    GET_USERDETAILS_FAIL = 'GET_USERDETAILS_FAIL'
}